#pragma once

namespace tsrebar {

enum class CommandId {
    ProjectNew,
    ProjectOpen,
    ProjectSave,
    ProjectClose,
    ImportStep,
    ExportRebarStep,
    EditUndo,
    EditRedo,
    EditDeleteSelection,
    SelectionPickMode,
    ReferenceCreatePlane,
    ReferenceCreateLine,
    ViewFitAll,
    ViewSelectFace,
    ViewSelectEdge,
    ViewSelectVertex,
    ViewPan,
    ViewZoom,
    ViewRotate,
    ViewRotateDiscrete,
    ViewZoomWindow,
    ViewIso,
    ViewPerpendicularToSelection,
    ViewRenderWireframe,
    RebarViewActivate,
    RebarViewDeactivate,
    RebarStyleOpenManager,
    ProjectSettings,
    ProjectSetElevationDatum,
    AppSystemSettings,
    RebarFaceCreate,
    RebarLineCreate,
    RebarArcGroupCreate,
    RebarSectionRingCreate,
    RebarFaceBoundaryCreate,
    RebarConcentricCircleCreate,
    RebarAngleCreate,
    RebarCustomCreate,
    RebarGenericCreate,
    RebarFixedCenterCreate,
    RebarStirrupCreate,
    RebarCornerCreate,
    RebarOpeningCreate,
    RebarInsertCreate,
    RebarSpiralCreate,
    RebarMove,
    RebarCopy,
    RebarGroupMerge,
    RebarGroupSplit,
    RebarSegmentConnect,
    RebarSegmentDisconnect,
    RebarAddBarCount,
    RebarAddSegment,
    RebarGroupTrimByLine,
    RebarGroupTrimByFace,
    QueryByNumber,
    QueryByDiameter,
    QueryByPart,
    QueryCollision,
    QueryUncutOrUnsectioned,
    QueryOutsideStructure,
    QueryMinDistance,
    QueryGroupMinDistance,
    MeasureGeneric,
    MeasureStructureProperty,
    DrawingDefineSectionPlane,
    DrawingDefineProjectPlane,
    DrawingDefineAxonometricProjection,
    DrawingGeneratePackage,
    DrawingGenerateBarSchedule
};

} // namespace tsrebar
