#include "command/LegacyUiCommandMap.h"

#include "command/CommandRegistry.h"

namespace tsrebar {

namespace {

LegacyUiCommandDefinition command(CommandId id,
                                  LegacyCommandUiSurface uiSurface,
                                  QString commandKey,
                                  QString caption,
                                  QString objectName,
                                  QString tabObjectName,
                                  QString groupObjectName,
                                  QString legacyUiPath,
                                  QVector<QString> evidenceIds,
                                  QVector<QString> sourceRefs = {},
                                  QVector<QString> gapIds = {},
                                  QVector<QString> inputSelectionTypes = {},
                                  QString legacyCommand = {},
                                  QString legacyContextCommandId = {},
                                  LegacyCommandImplementationState implementationState =
                                      LegacyCommandImplementationState::NotImplemented,
                                  QVector<LegacyCommandInteractionState> interactionStates =
                                      {LegacyCommandInteractionState::Idle,
                                       LegacyCommandInteractionState::Armed,
                                       LegacyCommandInteractionState::Picking,
                                       LegacyCommandInteractionState::Previewing,
                                       LegacyCommandInteractionState::Completed,
                                       LegacyCommandInteractionState::Cancelled,
                                       LegacyCommandInteractionState::Failed})
{
    return {id,
            uiSurface,
            std::move(commandKey),
            std::move(caption),
            std::move(objectName),
            std::move(tabObjectName),
            std::move(groupObjectName),
            std::move(legacyUiPath),
            std::move(legacyCommand),
            std::move(legacyContextCommandId),
            std::move(evidenceIds),
            std::move(sourceRefs),
            std::move(gapIds),
            std::move(inputSelectionTypes),
            implementationState,
            std::move(interactionStates)};
}

LegacyUiCommandDefinition ribbonCommand(CommandId id,
                                        QString commandKey,
                                        QString caption,
                                        QString objectName,
                                        QString tabObjectName,
                                        QString groupObjectName,
                                        QString legacyUiPath,
                                        QVector<QString> evidenceIds,
                                        QVector<QString> sourceRefs = {},
                                        QVector<QString> gapIds = {},
                                        QVector<QString> inputSelectionTypes = {},
                                        QString legacyCommand = {},
                                        QString legacyContextCommandId = {},
                                        LegacyCommandImplementationState implementationState =
                                            LegacyCommandImplementationState::NotImplemented)
{
    return command(id,
                   LegacyCommandUiSurface::Ribbon,
                   std::move(commandKey),
                   std::move(caption),
                   std::move(objectName),
                   std::move(tabObjectName),
                   std::move(groupObjectName),
                   std::move(legacyUiPath),
                   std::move(evidenceIds),
                   std::move(sourceRefs),
                   std::move(gapIds),
                   std::move(inputSelectionTypes),
                   std::move(legacyCommand),
                   std::move(legacyContextCommandId),
                   implementationState);
}

LegacyUiCommandDefinition contextMenuCommand(CommandId id,
                                             QString commandKey,
                                             QString caption,
                                             QString objectName,
                                             QString legacyUiPath,
                                             QVector<QString> evidenceIds,
                                             QVector<QString> sourceRefs = {},
                                             QVector<QString> gapIds = {},
                                             QVector<QString> inputSelectionTypes = {},
                                             QString legacyContextCommandId = {})
{
    return command(id,
                   LegacyCommandUiSurface::ContextMenu,
                   std::move(commandKey),
                   std::move(caption),
                   std::move(objectName),
                   {},
                   {},
                   std::move(legacyUiPath),
                   std::move(evidenceIds),
                   std::move(sourceRefs),
                   std::move(gapIds),
                   std::move(inputSelectionTypes),
                   {},
                   std::move(legacyContextCommandId));
}

QString placeholderMessage(const LegacyUiCommandDefinition& definition)
{
    return QStringLiteral("%1：该功能已登记，旧图石行为待确认，当前版本暂未实现。")
        .arg(definition.commandKey);
}

} // namespace

QVector<LegacyUiCommandDefinition> legacyUiCommands()
{
    return {
        ribbonCommand(CommandId::ProjectNew, QStringLiteral("Project.New"), QStringLiteral("新建"),
                QStringLiteral("cmd_project_new"), QStringLiteral("tab_start"),
                QStringLiteral("group_file"), QStringLiteral("开始/文件/新建"),
                {}, {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-START-001")}),
        ribbonCommand(CommandId::ProjectOpen, QStringLiteral("Project.Open"), QStringLiteral("打开"),
                QStringLiteral("cmd_project_open"), QStringLiteral("tab_start"),
                QStringLiteral("group_file"), QStringLiteral("开始/文件/打开"),
                {}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-START-002"), QStringLiteral("GAP-DEV-001")}),
        ribbonCommand(CommandId::ProjectSave, QStringLiteral("Project.Save"), QStringLiteral("保存"),
                QStringLiteral("cmd_project_save"), QStringLiteral("tab_start"),
                QStringLiteral("group_file"), QStringLiteral("开始/文件/保存"),
                {}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-START-003"), QStringLiteral("GAP-DEV-001")}),
        ribbonCommand(CommandId::ProjectClose, QStringLiteral("Project.Close"), QStringLiteral("关闭"),
                QStringLiteral("cmd_project_close"), QStringLiteral("tab_start"),
                QStringLiteral("group_file"), QStringLiteral("开始/文件/关闭"),
                {}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-START-004"), QStringLiteral("GAP-DEV-004")}),
        ribbonCommand(CommandId::ImportStep, QStringLiteral("Project.OpenStep"),
                QStringLiteral("导入 STEP"), QStringLiteral("cmd_import_step"),
                QStringLiteral("tab_start"), QStringLiteral("group_file"),
                QStringLiteral("开始/文件/打开"), {}, {QStringLiteral("36")}, {}, {},
                {}, {}, LegacyCommandImplementationState::Implemented),
        ribbonCommand(CommandId::ExportRebarStep, QStringLiteral("Rebar.Export.SteelStepOrLegacy"),
                QStringLiteral("输出钢筋"), QStringLiteral("cmd_export_rebar_step"),
                QStringLiteral("tab_start"), QStringLiteral("group_file"),
                QStringLiteral("开始/文件/输出钢筋"),
                {QStringLiteral("E-RUN-002"), QStringLiteral("E-IDA-014"),
                 QStringLiteral("E-DEV-023"),
                 QStringLiteral("E-DEV-048")},
                {}, {QStringLiteral("GAP-IDA-008")}, {},
                QStringLiteral("sexportbar/ysteelout")),
        ribbonCommand(CommandId::EditUndo, QStringLiteral("Edit.Undo"), QStringLiteral("放弃"),
                QStringLiteral("cmd_edit_undo"), QStringLiteral("tab_start"),
                QStringLiteral("group_edit"), QStringLiteral("开始/编辑/放弃"),
                {}, {QStringLiteral("17")},
                {QStringLiteral("GAP-DEV-003"), QStringLiteral("GAP-BTN-START-005")}),
        ribbonCommand(CommandId::EditRedo, QStringLiteral("Edit.Redo"), QStringLiteral("重做"),
                QStringLiteral("cmd_edit_redo"), QStringLiteral("tab_start"),
                QStringLiteral("group_edit"), QStringLiteral("开始/编辑/重做"),
                {}, {QStringLiteral("17")},
                {QStringLiteral("GAP-DEV-003"), QStringLiteral("GAP-BTN-START-006")}),
        ribbonCommand(CommandId::EditDeleteSelection, QStringLiteral("Edit.DeleteSelection"),
                QStringLiteral("删除"), QStringLiteral("cmd_edit_delete_selection"),
                QStringLiteral("tab_start"), QStringLiteral("group_edit"),
                QStringLiteral("开始/编辑/删除"), {}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-START-007")}, {QStringLiteral("selection")}),
        ribbonCommand(CommandId::SelectionPickMode, QStringLiteral("Selection.PickMode"),
                QStringLiteral("拾取"), QStringLiteral("cmd_selection_pick_mode"),
                QStringLiteral("tab_start"), QStringLiteral("group_reference"),
                QStringLiteral("开始/参考/拾取"), {}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-START-010")},
                {QStringLiteral("selection")}),
        ribbonCommand(CommandId::ReferenceCreatePlane, QStringLiteral("Reference.CreatePlane"),
                QStringLiteral("参考面"), QStringLiteral("cmd_reference_create_plane"),
                QStringLiteral("tab_start"), QStringLiteral("group_reference"),
                QStringLiteral("开始/参考/参考面"), {QStringLiteral("E-STR-参考面")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-START-008")}),
        ribbonCommand(CommandId::ReferenceCreateLine, QStringLiteral("Reference.CreateLine"),
                QStringLiteral("参考线"), QStringLiteral("cmd_reference_create_line"),
                QStringLiteral("tab_start"), QStringLiteral("group_reference"),
                QStringLiteral("开始/参考/参考线"), {QStringLiteral("E-DLG-317")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-START-009")}),
        ribbonCommand(CommandId::ViewFitAll, QStringLiteral("View.FitAll"), QStringLiteral("全显"),
                QStringLiteral("cmd_view_fit_all"), QStringLiteral("tab_view"),
                QStringLiteral("group_view"), QStringLiteral("显示/取景/全显"),
                {}, {QStringLiteral("17")}, {}, {}, {}, {},
                LegacyCommandImplementationState::Implemented),
        ribbonCommand(CommandId::ViewSelectFace, QStringLiteral("View.SelectFace"),
                QStringLiteral("选面"), QStringLiteral("cmd_view_select_face"),
                QStringLiteral("tab_view"), QStringLiteral("group_view"),
                QStringLiteral("显示/选择/选面"), {QStringLiteral("E-DEV-027")},
                {QStringLiteral("M1-App-003")},
                {}, {QStringLiteral("face")}, {}, {},
                LegacyCommandImplementationState::Implemented),
        ribbonCommand(CommandId::ViewSelectEdge, QStringLiteral("View.SelectEdge"),
                QStringLiteral("选边"), QStringLiteral("cmd_view_select_edge"),
                QStringLiteral("tab_view"), QStringLiteral("group_view"),
                QStringLiteral("显示/选择/选边"), {QStringLiteral("E-DEV-027")},
                {QStringLiteral("M1-App-003")},
                {}, {QStringLiteral("edge")}, {}, {},
                LegacyCommandImplementationState::Implemented),
        ribbonCommand(CommandId::ViewSelectVertex, QStringLiteral("View.SelectVertex"),
                QStringLiteral("选点"), QStringLiteral("cmd_view_select_vertex"),
                QStringLiteral("tab_view"), QStringLiteral("group_view"),
                QStringLiteral("显示/选择/选点"), {QStringLiteral("E-DEV-027")},
                {QStringLiteral("M1-App-003")},
                {}, {QStringLiteral("vertex")}, {}, {},
                LegacyCommandImplementationState::Implemented),
        ribbonCommand(CommandId::ViewPan, QStringLiteral("View.PanRealtime"),
                QStringLiteral("实时平移"), QStringLiteral("cmd_view_pan"),
                QStringLiteral("tab_view"), QStringLiteral("group_view"),
                QStringLiteral("显示/取景/实时平移"), {}, {QStringLiteral("17")}),
        ribbonCommand(CommandId::ViewZoom, QStringLiteral("View.ZoomRealtime"),
                QStringLiteral("实时缩放"), QStringLiteral("cmd_view_zoom"),
                QStringLiteral("tab_view"), QStringLiteral("group_view"),
                QStringLiteral("显示/取景/实时缩放"), {}, {QStringLiteral("17")}),
        ribbonCommand(CommandId::ViewRotate, QStringLiteral("View.OrbitRealtime"),
                QStringLiteral("实时转动"), QStringLiteral("cmd_view_rotate"),
                QStringLiteral("tab_view"), QStringLiteral("group_view"),
                QStringLiteral("显示/取景/实时转动"), {}, {QStringLiteral("17")}),
        ribbonCommand(CommandId::ViewZoomWindow, QStringLiteral("View.ZoomWindow"),
                QStringLiteral("窗口缩放"), QStringLiteral("cmd_view_zoom_window"),
                QStringLiteral("tab_view"), QStringLiteral("group_view"),
                QStringLiteral("显示/取景/窗口缩放"), {QStringLiteral("E-STR-窗口缩放")},
                {QStringLiteral("17")}),
        ribbonCommand(CommandId::ViewIso, QStringLiteral("View.Iso"),
                QStringLiteral("轴测"), QStringLiteral("cmd_view_iso"),
                QStringLiteral("tab_view"), QStringLiteral("group_view"),
                QStringLiteral("显示/视图/轴测"), {QStringLiteral("E-STR-轴测")},
                {QStringLiteral("17")}),
        ribbonCommand(CommandId::ViewPerpendicularToSelection,
                QStringLiteral("View.PerpendicularToSelection"), QStringLiteral("垂直于"),
                QStringLiteral("cmd_view_perpendicular_to_selection"),
                QStringLiteral("tab_view"), QStringLiteral("group_view"),
                QStringLiteral("显示/视图/垂直于"), {QStringLiteral("E-STR-垂直于")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-VIEW-001")},
                {QStringLiteral("face-or-edge")}),
        ribbonCommand(CommandId::ViewRotateDiscrete, QStringLiteral("View.Rotate"),
                QStringLiteral("旋转"), QStringLiteral("cmd_view_rotate_discrete"),
                QStringLiteral("tab_view"), QStringLiteral("group_view"),
                QStringLiteral("显示/视图/旋转"), {QStringLiteral("E-STR-旋转")},
                {QStringLiteral("17")}),
        ribbonCommand(CommandId::ViewRenderWireframe, QStringLiteral("View.Render.Wireframe"),
                QStringLiteral("线框"), QStringLiteral("cmd_view_render_wireframe"),
                QStringLiteral("tab_view"), QStringLiteral("group_display_state"),
                QStringLiteral("显示/显示状态/线框"), {QStringLiteral("E-STR-线框")},
                {QStringLiteral("17")}),
        ribbonCommand(CommandId::RebarViewActivate, QStringLiteral("Rebar.View.Activate"),
                QStringLiteral("激活"), QStringLiteral("cmd_rebar_view_activate"),
                QStringLiteral("tab_view"), QStringLiteral("group_display_state"),
                QStringLiteral("显示/显示状态/激活"), {QStringLiteral("E-STR-激活")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-DEV-004")},
                {QStringLiteral("rebar-or-group")}),
        ribbonCommand(CommandId::RebarViewDeactivate,
                QStringLiteral("Rebar.View.Deactivate"), QStringLiteral("钝化"),
                QStringLiteral("cmd_rebar_view_deactivate"),
                QStringLiteral("tab_view"), QStringLiteral("group_display_state"),
                QStringLiteral("显示/显示状态/钝化"), {QStringLiteral("E-STR-钝化")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-DEV-004")},
                {QStringLiteral("rebar-or-group")}),
        ribbonCommand(CommandId::RebarStyleOpenManager,
                QStringLiteral("RebarStyle.OpenManager"), QStringLiteral("钢筋式样"),
                QStringLiteral("cmd_rebar_style_open_manager"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_settings"),
                QStringLiteral("钢筋/文件属性/钢筋式样"),
                {QStringLiteral("E-DLG-292"), QStringLiteral("E-DLG-293")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-SET-001")}),
        ribbonCommand(CommandId::ProjectSettings, QStringLiteral("Project.Settings"),
                QStringLiteral("文件设置"), QStringLiteral("cmd_project_settings"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_settings"),
                QStringLiteral("钢筋/文件属性/文件设置"), {QStringLiteral("E-DLG-426")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-SET-002")}),
        ribbonCommand(CommandId::ProjectSetElevationDatum,
                QStringLiteral("Project.SetElevationDatum"), QStringLiteral("标高基准面"),
                QStringLiteral("cmd_project_set_elevation_datum"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_settings"),
                QStringLiteral("钢筋/文件属性/标高基准面"),
                {QStringLiteral("E-DLG-283")}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-SET-003")}),
        ribbonCommand(CommandId::AppSystemSettings, QStringLiteral("App.SystemSettings"),
                QStringLiteral("系统设置"), QStringLiteral("cmd_app_system_settings"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_settings"),
                QStringLiteral("钢筋/文件属性/系统设置"),
                {QStringLiteral("E-DLG-3011")}, {QStringLiteral("17")},
                {QStringLiteral("GAP-TECH-001")}),
        ribbonCommand(CommandId::RebarFaceCreate, QStringLiteral("Rebar.Create.Face"),
                QStringLiteral("面配筋"), QStringLiteral("cmd_rebar_face_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/主要钢筋/面配筋"),
                {QStringLiteral("E-DLG-265"), QStringLiteral("E-DLG-266"),
                 QStringLiteral("E-DLG-268"), QStringLiteral("E-SFL-001"),
                 QStringLiteral("E-RUN-001")},
                {},
                {QStringLiteral("GAP-DEV-004"), QStringLiteral("GAP-DEV-005"),
                 QStringLiteral("GAP-DEV-006")},
                {QStringLiteral("face"), QStringLiteral("direction-or-guide-line")}),
        ribbonCommand(CommandId::RebarLineCreate, QStringLiteral("Rebar.Create.LineGroup"),
                QStringLiteral("线配筋"), QStringLiteral("cmd_rebar_line_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/主要钢筋/线配筋"),
                {QStringLiteral("E-IDA-002"), QStringLiteral("E-IDA-010"),
                 QStringLiteral("E-IDA-012"), QStringLiteral("E-IDA-013"),
                 QStringLiteral("E-IDA-045"), QStringLiteral("E-DEV-093"),
                 QStringLiteral("E-STR-线配筋")},
                {},
                {QStringLiteral("GAP-IDA-002"), QStringLiteral("GAP-IDA-007")},
                {QStringLiteral("single-selected-entity-list"),
                 QStringLiteral("edge-p0-surrogate")},
                QStringLiteral("sgroupbarline"), {},
                LegacyCommandImplementationState::Implemented),
        ribbonCommand(CommandId::RebarArcGroupCreate, QStringLiteral("Rebar.Create.ArcGroup"),
                QStringLiteral("扇形筋"), QStringLiteral("cmd_rebar_arc_group_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/主要钢筋/扇形筋"),
                {QStringLiteral("E-IDA-001"), QStringLiteral("E-IDA-011"),
                 QStringLiteral("E-IDA-012"), QStringLiteral("E-IDA-013"),
                 QStringLiteral("E-STR-扇形筋")},
                {},
                {QStringLiteral("GAP-IDA-001"), QStringLiteral("GAP-IDA-007")},
                {QStringLiteral("single-selected-chain")},
                QStringLiteral("sgroupbararc")),
        ribbonCommand(CommandId::RebarSectionRingCreate,
                QStringLiteral("Rebar.Create.SectionRing"), QStringLiteral("剖面圈筋"),
                QStringLiteral("cmd_rebar_section_ring_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/主要钢筋/剖面圈筋"), {},
                {QStringLiteral("17")}, {QStringLiteral("GAP-FUNC-001")},
                {QStringLiteral("section-plane-or-face")}),
        ribbonCommand(CommandId::RebarFaceBoundaryCreate,
                QStringLiteral("Rebar.Create.FaceBoundary"), QStringLiteral("面周边"),
                QStringLiteral("cmd_rebar_face_boundary_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/主要钢筋/面周边"), {QStringLiteral("E-STR-面周边")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-REB-C-005")},
                {QStringLiteral("face")}),
        ribbonCommand(CommandId::RebarConcentricCircleCreate,
                QStringLiteral("Rebar.Create.ConcentricCircle"), QStringLiteral("同心圆"),
                QStringLiteral("cmd_rebar_concentric_circle_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/主要钢筋/同心圆"), {QStringLiteral("E-STR-同心圆")},
                {QStringLiteral("17")},
                {QStringLiteral("GAP-IDA-001"), QStringLiteral("GAP-BTN-REB-C-006")},
                {QStringLiteral("circle-or-chain")}),
        ribbonCommand(CommandId::RebarAngleCreate, QStringLiteral("Rebar.Create.Angle"),
                QStringLiteral("角度配筋"), QStringLiteral("cmd_rebar_angle_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/主要钢筋/角度配筋"),
                {QStringLiteral("E-STR-角度配筋")}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-REB-C-007")}),
        ribbonCommand(CommandId::RebarCustomCreate, QStringLiteral("Rebar.Create.Custom"),
                QStringLiteral("自配筋"), QStringLiteral("cmd_rebar_custom_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/主要钢筋/自配筋"),
                {QStringLiteral("E-STR-自配筋")}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-REB-C-008")}),
        ribbonCommand(CommandId::RebarGenericCreate, QStringLiteral("Rebar.Create.Generic"),
                QStringLiteral("钢筋配筋"), QStringLiteral("cmd_rebar_generic_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/主要钢筋/钢筋配筋"),
                {QStringLiteral("E-STR-钢筋配筋")}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-REB-C-009")}),
        ribbonCommand(CommandId::RebarFixedCenterCreate,
                QStringLiteral("Rebar.Create.FixedCenter"), QStringLiteral("固中心"),
                QStringLiteral("cmd_rebar_fixed_center_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/构造钢筋/固中心"), {}, {QStringLiteral("17")},
                {QStringLiteral("GAP-FUNC-002")}),
        ribbonCommand(CommandId::RebarStirrupCreate, QStringLiteral("Rebar.Create.Stirrup"),
                QStringLiteral("箍筋"), QStringLiteral("cmd_rebar_stirrup_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/构造钢筋/箍筋"), {QStringLiteral("E-STR-箍筋")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-REB-C-010")}),
        ribbonCommand(CommandId::RebarCornerCreate, QStringLiteral("Rebar.Create.Corner"),
                QStringLiteral("角筋"), QStringLiteral("cmd_rebar_corner_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/构造钢筋/角筋"), {QStringLiteral("E-STR-角筋")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-REB-C-011")}),
        ribbonCommand(CommandId::RebarOpeningCreate, QStringLiteral("Rebar.Create.Opening"),
                QStringLiteral("孔口"), QStringLiteral("cmd_rebar_opening_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/构造钢筋/孔口"), {QStringLiteral("E-STR-孔口")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-REB-C-012")}),
        ribbonCommand(CommandId::RebarInsertCreate, QStringLiteral("Rebar.Create.Insert"),
                QStringLiteral("插筋"), QStringLiteral("cmd_rebar_insert_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/构造钢筋/插筋"), {QStringLiteral("E-STR-插筋")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-REB-C-014")}),
        ribbonCommand(CommandId::RebarSpiralCreate, QStringLiteral("Rebar.Create.Spiral"),
                QStringLiteral("螺旋筋"), QStringLiteral("cmd_rebar_spiral_create"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_create"),
                QStringLiteral("钢筋/构造钢筋/螺旋筋"),
                {QStringLiteral("E-STR-螺旋筋")}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-REB-C-015")}),
        ribbonCommand(CommandId::RebarMove, QStringLiteral("Rebar.Edit.Move"),
                QStringLiteral("钢筋移动"), QStringLiteral("cmd_rebar_move"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_edit"),
                QStringLiteral("钢筋/钢筋编辑/钢筋移动"), {QStringLiteral("E-IDA-004")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-DEV-004")},
                {QStringLiteral("rebar-or-group")}, QStringLiteral("barmove")),
        ribbonCommand(CommandId::RebarCopy, QStringLiteral("Rebar.Edit.Copy"),
                QStringLiteral("钢筋拷贝"), QStringLiteral("cmd_rebar_copy"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_edit"),
                QStringLiteral("钢筋/钢筋编辑/钢筋拷贝"),
                {QStringLiteral("E-DLG-384")}, {QStringLiteral("17")},
                {QStringLiteral("GAP-DEV-003")},
                {QStringLiteral("rebar-or-group")}),
        ribbonCommand(CommandId::RebarGroupMerge, QStringLiteral("Rebar.Group.Merge"),
                QStringLiteral("组合并"), QStringLiteral("cmd_rebar_group_merge"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_edit"),
                QStringLiteral("钢筋/钢筋编辑/组合并"),
                {QStringLiteral("E-DLG-500"), QStringLiteral("E-CTX-891F")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-DEV-005")},
                {QStringLiteral("rebar-groups")}),
        ribbonCommand(CommandId::RebarGroupSplit, QStringLiteral("Rebar.Group.Split"),
                QStringLiteral("组合开"), QStringLiteral("cmd_rebar_group_split"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_edit"),
                QStringLiteral("钢筋/钢筋编辑/组合开"), {}, {QStringLiteral("17")},
                {QStringLiteral("GAP-FUNC-003")}, {QStringLiteral("rebar-group")}),
        ribbonCommand(CommandId::RebarSegmentConnect,
                QStringLiteral("Rebar.Segment.Connect"), QStringLiteral("段连接"),
                QStringLiteral("cmd_rebar_segment_connect"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_edit"),
                QStringLiteral("钢筋/钢筋编辑/段连接"),
                {QStringLiteral("E-DLG-499"), QStringLiteral("E-CTX-8924")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-DEV-005")},
                {QStringLiteral("rebar-segments")}),
        ribbonCommand(CommandId::RebarSegmentDisconnect,
                QStringLiteral("Rebar.Segment.Disconnect"), QStringLiteral("段断开"),
                QStringLiteral("cmd_rebar_segment_disconnect"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_edit"),
                QStringLiteral("钢筋/钢筋编辑/段断开"),
                {QStringLiteral("E-STR-段断开")}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-REB-E-006")},
                {QStringLiteral("rebar-segments")}),
        ribbonCommand(CommandId::RebarAddBarCount,
                QStringLiteral("Rebar.Edit.AddBarCount"), QStringLiteral("增加钢筋根数"),
                QStringLiteral("cmd_rebar_add_bar_count"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_edit"),
                QStringLiteral("钢筋/钢筋编辑/增加钢筋根数"),
                {QStringLiteral("E-STR-增加钢筋根数")}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-REB-E-007")},
                {QStringLiteral("rebar-group")}),
        ribbonCommand(CommandId::RebarAddSegment,
                QStringLiteral("Rebar.Edit.AddSegment"), QStringLiteral("增加钢筋段"),
                QStringLiteral("cmd_rebar_add_segment"),
                QStringLiteral("tab_rebar"), QStringLiteral("group_rebar_edit"),
                QStringLiteral("钢筋/钢筋编辑/增加钢筋段"),
                {QStringLiteral("E-DLG-392")}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-REB-E-008")},
                {QStringLiteral("rebar-or-group")}),
        contextMenuCommand(CommandId::RebarGroupTrimByLine,
                           QStringLiteral("RebarGroup.TrimByLine"),
                           QStringLiteral("与线裁剪"),
                           QStringLiteral("cmd_rebar_group_trim_by_line"),
                           QStringLiteral("钢筋/右键菜单/与线裁剪"),
                           {QStringLiteral("E-CTX-8939")},
                           {},
                           {QStringLiteral("GAP-IDA-007")},
                           {QStringLiteral("rebar-group+line")},
                           QStringLiteral("0x8939")),
        contextMenuCommand(CommandId::RebarGroupTrimByFace,
                           QStringLiteral("RebarGroup.TrimByFace"),
                           QStringLiteral("与面裁剪"),
                           QStringLiteral("cmd_rebar_group_trim_by_face"),
                           QStringLiteral("钢筋/右键菜单/与面裁剪"),
                           {QStringLiteral("E-CTX-8CE5")},
                           {},
                           {QStringLiteral("GAP-IDA-007")},
                           {QStringLiteral("rebar-group+face")},
                           QStringLiteral("0x8CE5")),
        ribbonCommand(CommandId::QueryByNumber, QStringLiteral("Rebar.Query.ByNumber"),
                QStringLiteral("按编号"), QStringLiteral("cmd_query_by_number"),
                QStringLiteral("tab_query"), QStringLiteral("group_rebar_query"),
                QStringLiteral("查询/查询钢筋/按编号"), {QStringLiteral("E-DLG-303")}),
        ribbonCommand(CommandId::QueryByDiameter, QStringLiteral("Rebar.Query.ByDiameter"),
                QStringLiteral("按直径"), QStringLiteral("cmd_query_by_diameter"),
                QStringLiteral("tab_query"), QStringLiteral("group_rebar_query"),
                QStringLiteral("查询/查询钢筋/按直径"), {QStringLiteral("E-STR-按直径")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-QUERY-001")}),
        ribbonCommand(CommandId::QueryByPart, QStringLiteral("Rebar.Query.ByPart"),
                QStringLiteral("按部位"), QStringLiteral("cmd_query_by_part"),
                QStringLiteral("tab_query"), QStringLiteral("group_rebar_query"),
                QStringLiteral("查询/查询钢筋/按部位"), {QStringLiteral("E-DLG-486")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-QUERY-002")}),
        ribbonCommand(CommandId::QueryCollision, QStringLiteral("Rebar.Check.Overlap"),
                QStringLiteral("碰撞检测"), QStringLiteral("cmd_query_collision"),
                QStringLiteral("tab_query"), QStringLiteral("group_rebar_check"),
                QStringLiteral("查询/测量/碰撞检测"),
                {QStringLiteral("E-IDA-007"), QStringLiteral("E-DLG-449")},
                {}, {}, {QStringLiteral("rebar-model")}),
        ribbonCommand(CommandId::QueryUncutOrUnsectioned,
                QStringLiteral("Rebar.Check.UncutOrUnsectioned"),
                QStringLiteral("未割钢筋"), QStringLiteral("cmd_query_uncut_rebar"),
                QStringLiteral("tab_query"), QStringLiteral("group_rebar_check"),
                QStringLiteral("查询/检查/未割钢筋"),
                {QStringLiteral("E-DLG-438"), QStringLiteral("E-DLG-1404")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-FUNC-004")},
                {QStringLiteral("rebar-model")}),
        ribbonCommand(CommandId::QueryOutsideStructure,
                QStringLiteral("Rebar.Check.OutsideStructure"),
                QStringLiteral("体外钢筋"), QStringLiteral("cmd_query_outside_structure"),
                QStringLiteral("tab_query"), QStringLiteral("group_rebar_check"),
                QStringLiteral("查询/检查/体外钢筋"),
                {QStringLiteral("E-STR-体外钢筋")}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-QUERY-003")},
                {QStringLiteral("rebar-model")}),
        ribbonCommand(CommandId::MeasureGeneric, QStringLiteral("Measure.Generic"),
                QStringLiteral("测量"), QStringLiteral("cmd_measure_generic"),
                QStringLiteral("tab_query"), QStringLiteral("group_rebar_check"),
                QStringLiteral("查询/测量/测量"), {QStringLiteral("E-DLG-116")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-QUERY-004")}),
        ribbonCommand(CommandId::MeasureStructureProperty,
                QStringLiteral("Measure.StructureProperty"), QStringLiteral("结构属性"),
                QStringLiteral("cmd_measure_structure_property"),
                QStringLiteral("tab_query"), QStringLiteral("group_rebar_check"),
                QStringLiteral("查询/测量/结构属性"),
                {QStringLiteral("E-STR-结构属性")}, {QStringLiteral("17")},
                {QStringLiteral("GAP-BTN-QUERY-005")}),
        ribbonCommand(CommandId::QueryMinDistance, QStringLiteral("Rebar.Check.MinDistance"),
                QStringLiteral("主筋"), QStringLiteral("cmd_query_min_distance"),
                QStringLiteral("tab_query"), QStringLiteral("group_rebar_check"),
                QStringLiteral("查询/测量/主筋"),
                {QStringLiteral("E-IDA-008"), QStringLiteral("E-DLG-450"),
                 QStringLiteral("E-DEV-036")},
                {}, {}, {QStringLiteral("rebar-model")}),
        ribbonCommand(CommandId::QueryGroupMinDistance,
                QStringLiteral("Rebar.Check.GroupMinDistance"), QStringLiteral("箍筋"),
                QStringLiteral("cmd_query_group_min_distance"),
                QStringLiteral("tab_query"), QStringLiteral("group_rebar_check"),
                QStringLiteral("查询/测量/箍筋"),
                {QStringLiteral("E-IDA-009"), QStringLiteral("E-DLG-450")},
                {}, {QStringLiteral("GAP-BTN-QUERY-006")},
                {QStringLiteral("rebar-model")}),
        ribbonCommand(CommandId::DrawingDefineSectionPlane,
                QStringLiteral("Drawing.DefineSectionPlane"), QStringLiteral("剖切面"),
                QStringLiteral("cmd_drawing_section_plane"), QStringLiteral("tab_drawing"),
                QStringLiteral("group_drawing_view"),
                QStringLiteral("工程图/定义视图/剖切面"),
                {QStringLiteral("E-DLG-316"), QStringLiteral("E-DLG-485"),
                 QStringLiteral("E-SFL-002")},
                {}, {QStringLiteral("GAP-FUNC-005")}),
        ribbonCommand(CommandId::DrawingDefineProjectPlane,
                QStringLiteral("Drawing.DefineProjectPlane"), QStringLiteral("投影面"),
                QStringLiteral("cmd_drawing_project_plane"), QStringLiteral("tab_drawing"),
                QStringLiteral("group_drawing_view"),
                QStringLiteral("工程图/定义视图/投影面"),
                {QStringLiteral("E-DLG-269"), QStringLiteral("E-SFL-003")}),
        ribbonCommand(CommandId::DrawingDefineAxonometricProjection,
                QStringLiteral("Drawing.DefineAxonometricProjection"),
                QStringLiteral("轴测投影"),
                QStringLiteral("cmd_drawing_axonometric_projection"),
                QStringLiteral("tab_drawing"), QStringLiteral("group_drawing_view"),
                QStringLiteral("工程图/定义视图/轴测投影"),
                {QStringLiteral("E-DLG-484")},
                {QStringLiteral("17")}, {QStringLiteral("GAP-BTN-DRAW-001")}),
        ribbonCommand(CommandId::DrawingGeneratePackage,
                QStringLiteral("Drawing.GeneratePackage"), QStringLiteral("生成工程图"),
                QStringLiteral("cmd_drawing_generate_package"),
                QStringLiteral("tab_drawing"), QStringLiteral("group_drawing_output"),
                QStringLiteral("工程图/输出/生成工程图"), {QStringLiteral("E-DLG-274")}),
        ribbonCommand(CommandId::DrawingGenerateBarSchedule,
                QStringLiteral("Drawing.GenerateBarSchedule"), QStringLiteral("下料表"),
                QStringLiteral("cmd_drawing_bar_schedule"), QStringLiteral("tab_drawing"),
                QStringLiteral("group_drawing_output"), QStringLiteral("工程图/输出/下料表"),
                {QStringLiteral("E-DLG-427"), QStringLiteral("E-IDA-019"),
                 QStringLiteral("E-IDA-020"), QStringLiteral("E-IDA-021")},
                {},
                {QStringLiteral("GAP-IDA-006"), QStringLiteral("GAP-DRAW-004")},
                {QStringLiteral("rebar-model")}, QStringLiteral("psexcel"),
                QStringLiteral("0x8D1C")),
    };
}

bool hasLegacyUiCommand(CommandId id)
{
    const auto commands = legacyUiCommands();
    for (const auto& command : commands) {
        if (command.id == id) {
            return true;
        }
    }
    return false;
}

std::optional<LegacyUiCommandDefinition> legacyUiCommandDefinition(CommandId id)
{
    const auto commands = legacyUiCommands();
    for (const auto& command : commands) {
        if (command.id == id) {
            return command;
        }
    }
    return std::nullopt;
}

void registerLegacyUiCommandPlaceholders(CommandRegistry& registry)
{
    const auto commands = legacyUiCommands();
    for (const auto& commandDefinition : commands) {
        if (registry.hasHandler(commandDefinition.id) ||
            commandDefinition.implementationState == LegacyCommandImplementationState::Implemented) {
            continue;
        }

        registry.registerHandler(commandDefinition.id, [commandDefinition]() {
            return CommandResult{CommandStatus::NotImplemented,
                                 placeholderMessage(commandDefinition)};
        });
    }
}

} // namespace tsrebar
